/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "git-2020-02-28-b6879b6-QtAV"
#endif /* AVUTIL_FFVERSION_H */
